# Generated by Django 4.2.17 on 2025-04-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="review",
        ),
    ]
